sudo: required
dist: bionic
language: node_js
node_js:
    - '12.6.0'
cache:
    directories:
        - 'node_modules'
addons:
    ssh_known_hosts: 18.195.102.38
branches:
    only:
        - master
before_install:
    - openssl aes-256-cbc -K $encrypted_15807635012b_key -iv $encrypted_15807635012b_iv -in spotishare.pem.enc -out spotishare.pem -d
    - eval "$(ssh-agent -s)"
    - chmod 600 spotishare.pem
    - ssh-add spotishare.pem
install:
    - npm install
script:
    - npm test
after_success:
    - bash .scripts/install.sh
